#!/usr/bin/python
from uninformed import SudokuBoard
tiny = SudokuBoard("tiny.txt")
print("tiny: dfs")
(board, space, time) = tiny.dfs()
SudokuBoard.printBoard(board)
print("space: " + str(space) + "; time: " + str(time))
print("tiny: bfs")
(board,space,time) = tiny.bfs()
print("space: " + str(space) + "; time: " + str(time))
print("tiny: Simulated Annealing")
(board,downhill, rejects, uphill) = tiny.simAnneal(10000)
SudokuBoard.printBoard(board)
print("downhill moves: " + str(downhill))
print("Uphill rejects: " + str(rejects))
print("Uphill moves: " + str(uphill))

easy = SudokuBoard("easy.txt")
print("easy: dfs")
(board,space,time) = easy.dfs(True)
print("space: " + str(space) + "; time: " + str(time))
print("easy: bfs")
(board,space,time) = easy.bfs(True)
print("space: " + str(space) + "; time: " + str(time))
print("easy: Simulated Annealing")
(board,downhill, rejects, uphill) = easy.simAnneal(10000)
SudokuBoard.printBoard(board)
print("downhill moves: " + str(downhill))
print("Uphill rejects: " + str(rejects))
print("Uphill moves: " + str(uphill))

medium = SudokuBoard("medium.txt")

print("medium: dfs")
(board,space,time) = medium.dfs(True)
print("space: " + str(space) + "; time: " + str(time))
print("medium: bfs")
(board,space,time) = medium.bfs(True)
print("space: " + str(space) + "; time: " + str(time))
print("medium: Simulated Annealing")
(board,downhill, rejects, uphill) = medium.simAnneal(10000)
SudokuBoard.printBoard(board)
print("downhill moves: " + str(downhill))
print("Uphill rejects: " + str(rejects))
print("Uphill moves: " + str(uphill))
